//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESAgentList_
    {
        public string Agences_de__Wilaya { get; set; }
        public string username { get; set; }
        public string NOMS { get; set; }
        public string PRENOMS { get; set; }
        public string MATRICULE { get; set; }
        public Nullable<System.DateTime> DATE_RECRUTEMENT { get; set; }
        public string POSTE_OCCUPE { get; set; }
        public string DIPLOME_ { get; set; }
    }
}
