//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class action_User_Request
    {
        public string id_action { get; set; }
        public Nullable<int> id_request { get; set; }
        public Nullable<int> Year_Request { get; set; }
        public Nullable<int> NumWilaya_Request { get; set; }
        public string id_user { get; set; }
        public Nullable<System.DateTime> date_action { get; set; }
        public string action { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Request Request { get; set; }
    }
}
