//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAL_User
    {
        public string Id_Message { get; set; }
        public string Message { get; set; }
        public string id_user { get; set; }
        public string State_Message { get; set; }
        public string link { get; set; }
        public string Id_User_Destination { get; set; }
        public Nullable<System.DateTime> Date_Message { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
