//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public string Guid { get; set; }
        public string Link1 { get; set; }
        public Nullable<int> Id_Request { get; set; }
        public Nullable<int> NumWilaya_Request { get; set; }
        public Nullable<int> Year_Request { get; set; }
        public string extension { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
