//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objet_Disp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objet_Disp()
        {
            this.DispositionPrise = new HashSet<DispositionPrise>();
            this.Motif = new HashSet<Motif>();
        }
    
        public string id_objet { get; set; }
        public string objet { get; set; }
        public Nullable<int> ObjectNum { get; set; }
        public Nullable<System.Guid> PhaseId { get; set; }
    
        public virtual PhaseObject PhaseObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispositionPrise> DispositionPrise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Motif> Motif { get; set; }
    }
}
