//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions_Role
    {
        public string Id_Permission { get; set; }
        public string Id_Role { get; set; }
        public string Permission_Type { get; set; }
        public string Permission_Value { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
    }
}
