//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class relance
    {
        public string id_relances { get; set; }
        public Nullable<int> id_requete { get; set; }
        public Nullable<int> Year_Request { get; set; }
        public Nullable<int> NumWilaya_Request { get; set; }
        public string id_transmission { get; set; }
        public Nullable<System.DateTime> date_relance { get; set; }
        public string Description_relance { get; set; }
    
        public virtual Transmission Transmission { get; set; }
        public virtual Request Request { get; set; }
    }
}
