//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class requerant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requerant()
        {
            this.Request = new HashSet<Request>();
        }
    
        public string num { get; set; }
        public string nom_requerant { get; set; }
        public string prenom_requerant { get; set; }
        public string SEXE { get; set; }
        public Nullable<System.DateTime> Date_Naissance { get; set; }
        public string Adresse { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public Nullable<int> id_wilaya { get; set; }
        public string Nom_CAnimateur { get; set; }
        public string Prenom_CAnimateur { get; set; }
        public string Num_Dossier { get; set; }
    
        public virtual wilayas wilayas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
