//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.action_User_Request = new HashSet<action_User_Request>();
            this.Links = new HashSet<Link>();
            this.Message_Request = new HashSet<Message_Request>();
            this.relances = new HashSet<relance>();
        }
    
        public int num { get; set; }
        public int Year { get; set; }
        public int num_wilaya { get; set; }
        public Nullable<System.Guid> CommuneId { get; set; }
        public Nullable<int> id_state { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> Date_Insertion { get; set; }
        public string id_type { get; set; }
        public string num_requerant { get; set; }
        public string corp_requete { get; set; }
        public string id_trans { get; set; }
        public string result_traitement { get; set; }
        public Nullable<System.DateTime> Date_Envoi { get; set; }
        public string Ref_Validation { get; set; }
        public string id_Voie_Trans { get; set; }
        public string User_Inserted { get; set; }
        public Nullable<System.Guid> MotifId { get; set; }
        public Nullable<System.Guid> DispositionPriseId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<action_User_Request> action_User_Request { get; set; }
        public virtual Communes Commune { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Link> Links { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message_Request> Message_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relance> relances { get; set; }
        public virtual requerant requerant { get; set; }
        public virtual State_Request State_Request { get; set; }
        public virtual Transmission Transmission { get; set; }
        public virtual types types { get; set; }
        public virtual Voie_Transmission Voie_Transmission { get; set; }
        public virtual DispositionPrise DispositionPrise { get; set; }
        public virtual Motif Motif { get; set; }
    }
}
