//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructureWilaya
    {
        public System.Guid WilayaStructureId { get; set; }
        public Nullable<int> WilayaNum { get; set; }
        public Nullable<System.Guid> StructureId { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual Structure Structure { get; set; }
        public virtual wilayas wilayas { get; set; }
    }
}
