//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Structure()
        {
            this.StructureUser = new HashSet<StructureUser>();
            this.StructureWilaya = new HashSet<StructureWilaya>();
            this.UserManageStructure = new HashSet<UserManageStructure>();
        }
    
        public System.Guid StructureId { get; set; }
        public string IntituleFr { get; set; }
        public string IntituleAr { get; set; }
        public Nullable<System.Guid> LevelId { get; set; }
        public Nullable<System.Guid> StructureParentId { get; set; }
    
        public virtual LevelOfStrucure LevelOfStrucure { get; set; }
        public virtual Structure Structure1 { get; set; }
        public virtual Structure Structure2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StructureUser> StructureUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StructureWilaya> StructureWilaya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserManageStructure> UserManageStructure { get; set; }
    }
}
